/** 職種（goal_id）ごとに 1 つずつ厳選したスクール・転職サービス。同じスクールを複数の職種に載せるときはコースを分ける */
export type JobCategoryPick = {
  goalId: string;
  name: string;
  /** 学習ロードマップに対応するコース名（スクールのみ） */
  course?: string;
  /** この職種に合う理由（1 文。「おすすめ」とは書かず、事実ベースで書く） */
  fit: string;
  officialUrl: string;
  /** コースがカバーする学習ロードマップのステップ（data/learning-paths の step_id） */
  coveredStepIds?: string[];
  /** ASP の広告リンクに差し替えたら true にする（rel="sponsored nofollow" になる） */
  sponsored: boolean;
};

export const SCHOOL_PICKS: JobCategoryPick[] = [
  {
    goalId: "frontend-developer",
    name: "Tech Mentor（テックメンター）",
    course: "Webエンジニア就職コース（React）",
    fit: "React を中心に、フロントエンドエンジニアとしての就職までマンツーマンで指導",
    officialUrl: "https://tech-mentor.dev/",
    sponsored: false,
  },
  {
    goalId: "backend-developer",
    name: "ポテパンキャンプ",
    course: "Railsキャリアコース",
    fit: "Ruby on Rails で、Web 系自社開発企業へのバックエンド転職を目指すコース",
    officialUrl: "https://camp.potepan.com/courses/rails-career",
    coveredStepIds: ["backend-language", "git-github", "linux", "sql", "web-api", "backend-framework", "database-design", "testing", "docker"],
    sponsored: false,
  },
  {
    goalId: "full-stack-developer",
    name: "RUNTEQ（ランテック）",
    course: "Web開発スタンダードコース",
    fit: "画面からサーバー・データベースまで、Web アプリを一通り作れるようになるコース",
    officialUrl: "https://runteq.jp/",
    coveredStepIds: ["html-css", "javascript", "git-github", "backend-framework", "sql", "web-api", "testing", "cloud"],
    sponsored: false,
  },
  {
    goalId: "data-analyst",
    name: "Aidemy（アイデミー）",
    course: "Aidemy Premium データ分析講座",
    fit: "SQL・統計・Python・可視化など、データ分析の基礎を一通り学べる講座",
    officialUrl: "https://aidemy.net/",
    coveredStepIds: ["sql", "statistics", "data-visualization", "data-language", "dataframe", "git-github"],
    sponsored: false,
  },
  {
    goalId: "data-scientist",
    name: "データラーニングスクール",
    course: "データサイエンス講座",
    fit: "Python・統計から機械学習・深層学習まで、データサイエンティストに必要な範囲を扱う講座",
    officialUrl: "https://school.data-learning.com/",
    coveredStepIds: [
      "data-language",
      "sql",
      "statistics",
      "dataframe",
      "data-visualization",
      "math-for-ml",
      "git-github",
      "machine-learning",
      "deep-learning",
      "cloud",
    ],
    sponsored: false,
  },
  {
    goalId: "data-engineer",
    name: "データミックス",
    course: "データエンジニア育成講座",
    fit: "ETL・DWH・データモデリングなど、データ基盤の構築に絞った専門講座",
    officialUrl: "https://datamix.co.jp/school/expert/dataengineer/",
    coveredStepIds: ["sql", "data-engineering-language", "database-design", "data-modeling", "etl", "data-warehouse", "cloud", "docker"],
    sponsored: false,
  },
  {
    goalId: "it-project-manager",
    name: "アイシンク",
    course: "PMP®試験対策講座（個人向け公開講座）",
    fit: "PMBOK に沿って、計画・リスク・ステークホルダー管理を体系的に学ぶ PMI 認定講座",
    officialUrl: "https://www.i-think.co.jp/open-seminar/acquisition-online/",
    coveredStepIds: ["project-management", "agile-scrum", "risk-management", "stakeholder-management"],
    sponsored: false,
  },
  {
    goalId: "product-manager",
    name: "PM School",
    course: "コンプリートプラン",
    fit: "ユーザーリサーチ・要件定義・KPI・ロードマップなど、PdM の業務を一通り学べる",
    officialUrl: "https://pm-school.jp/",
    coveredStepIds: [
      "user-research",
      "requirements-definition",
      "ux-design",
      "product-metrics",
      "agile-scrum",
      "product-roadmap",
      "stakeholder-management",
    ],
    sponsored: false,
  },
  {
    goalId: "software-architect",
    name: "CTC教育サービス",
    course: "ITアーキテクト向け公開講座",
    fit: "システム設計・クラウド・セキュリティなど、アーキテクト向けの技術講座を個人でも受講できる",
    officialUrl: "https://www.school.ctc-g.co.jp/itarchitect/",
    sponsored: false,
  },
  {
    goalId: "mobile-app-developer",
    name: "TechAcademy（テックアカデミー）",
    fit: "iPhone アプリ・Android アプリの開発コースがあり、モバイル開発を現役エンジニアのメンターと学べる",
    officialUrl: "https://techacademy.jp/",
    sponsored: false,
  },
  {
    goalId: "network-engineer",
    name: "ウズウズカレッジ",
    course: "CCNAコース",
    fit: "ネットワークの標準資格 CCNA の取得と、インフラエンジニアとしての就職サポートが一体",
    officialUrl: "https://uzuz-college.jp/ccna/",
    coveredStepIds: ["network-fundamentals", "routing-switching", "network-security", "automation-scripting"],
    sponsored: false,
  },
  {
    goalId: "test-analyst",
    name: "Tech Mentor（テックメンター）",
    course: "ソフトウェアテストコース",
    fit: "テスト設計の資格 JSTQB FL の取得とテスト自動化の基礎、テストエンジニア就職のサポートまで",
    officialUrl: "https://tech-mentor.dev/software_test",
    coveredStepIds: ["sdlc", "test-design", "test-scripting-language", "test-automation"],
    sponsored: false,
  },
  {
    goalId: "devops-sre",
    name: "カサレアル クラウドネイティブ道場",
    course: "全体像から理解するクラウドネイティブ基礎 ほか",
    fit: "Docker・Kubernetes・CI/CD・IaC・監視をハンズオンで学ぶ公開講座（1 人から申込可）",
    officialUrl: "https://learning.casareal.co.jp/search/cloudnative-dojo",
    coveredStepIds: ["docker", "ci-cd", "cloud", "iac", "kubernetes", "monitoring"],
    sponsored: false,
  },
  {
    goalId: "cloud-architect",
    name: "RaiseTech（レイズテック）",
    course: "AWSフルコース",
    fit: "AWS を中心に、クラウドの設計・構築・自動化を実践課題で学ぶコース",
    officialUrl: "https://raise-tech.net/",
    coveredStepIds: ["cloud", "cloud-networking", "cloud-security", "docker", "iac", "system-design", "monitoring"],
    sponsored: false,
  },
];

export const JOB_SERVICE_PICKS: JobCategoryPick[] = [
  {
    goalId: "frontend-developer",
    name: "paiza転職",
    fit: "スキルチェックで実力を示して応募でき、React・Vue などフロントエンドの求人も探せる",
    officialUrl: "https://paiza.jp/career",
    sponsored: false,
  },
  {
    goalId: "backend-developer",
    name: "テックゴー",
    fit: "バックエンド・フルスタックの求人に強い、エンジニア専門の転職エージェント（実務経験者向け）",
    officialUrl: "https://tech-go.jp/",
    sponsored: false,
  },
  {
    goalId: "full-stack-developer",
    name: "ワークポート",
    fit: "開発からインフラまで IT 職種を幅広く扱い、未経験から経験者まで相談できる",
    officialUrl: "https://www.workport.co.jp/",
    sponsored: false,
  },
  {
    goalId: "data-analyst",
    name: "転職ドラフト",
    fit: "経歴やスキルを見た企業が年収を提示して指名する形式で、データアナリストの求人も扱う",
    officialUrl: "https://job-draft.jp/",
    sponsored: false,
  },
  {
    goalId: "data-scientist",
    name: "Symbiorise（シンビオライズ）",
    fit: "AI・機械学習・データサイエンス領域に絞った転職エージェント",
    officialUrl: "https://symbiorise.com/",
    sponsored: false,
  },
  {
    goalId: "data-engineer",
    name: "Findy",
    fit: "GitHub の活動から技術力を示せるエンジニア向け転職サービスで、データエンジニアの求人も扱う",
    officialUrl: "https://findy-code.io/",
    sponsored: false,
  },
  {
    goalId: "it-project-manager",
    name: "Geekly（ギークリー）",
    fit: "IT・Web・ゲーム業界に特化し、PM・PL の求人を扱う転職エージェント",
    officialUrl: "https://www.geekly.co.jp/",
    sponsored: false,
  },
  {
    goalId: "product-manager",
    name: "Offers Jobs",
    fit: "PdM・PM の職種カテゴリがあり、スタートアップや SaaS 企業の求人が中心",
    officialUrl: "https://offers.jp/",
    sponsored: false,
  },
  {
    goalId: "software-architect",
    name: "ビズリーチ",
    fit: "アーキテクト・テックリードなどのハイクラス求人で、企業やヘッドハンターからスカウトが届く",
    officialUrl: "https://www.bizreach.jp/",
    sponsored: false,
  },
  {
    goalId: "mobile-app-developer",
    name: "Green",
    fit: "Swift・Kotlin・Flutter などの技術で求人を絞り込め、自社開発企業に直接応募できる",
    officialUrl: "https://www.green-japan.com/",
    sponsored: false,
  },
  {
    goalId: "network-engineer",
    name: "マイナビIT AGENT",
    fit: "IT・Web 業界に特化した転職エージェントで、ネットワーク・インフラ職の求人も扱う",
    officialUrl: "https://mynavi-agent.jp/it/",
    sponsored: false,
  },
  {
    goalId: "test-analyst",
    name: "レバテックダイレクト",
    fit: "QA・テストエンジニアの職種カテゴリがある、エンジニア向けスカウトサービス",
    officialUrl: "https://levtech-direct.jp/",
    sponsored: false,
  },
  {
    goalId: "devops-sre",
    name: "レバテックフリーランス",
    fit: "SRE・クラウド・インフラの案件を扱う、実務経験者向けのフリーランスエージェント",
    officialUrl: "https://freelance.levtech.jp/",
    sponsored: false,
  },
  {
    goalId: "cloud-architect",
    name: "ソリューションパートナー",
    fit: "インフラ・クラウドエンジニア向けの転職エージェントで、設計・構築の求人を扱う",
    officialUrl: "https://sol-partner.co.jp/",
    sponsored: false,
  },
];
